#!/bin/bash

# Create dir
name="$(printf "day%02d" "$1")"
mkdir "$name" && cd "$name"
cargo new --bin "rust"
mkdir "python"
touch "python/main.py"
URL="https://adventofcode.com/2023/day/$1/input"
curl "$URL" --cookie "session=$AOC_SESSION" -s | tee "input"
